### ISSUE TITLE
Fail to read *.png like binary file

### ISSUE THREAD

**Issue by hxgqh** [skpm/fs#1]
fs.readFile('xxx.png') return null

**Comment by hxgqh** [comment]
The following code works:

    function getFileSuffix(file){
      if(!file){
        return null;
      }

      if(file.indexOf('.') < 0){
        return null;
      }

      let arr = file.split('.');
      return arr[arr.length - 1];
    }

    function readFileBase64(file) {
      let bitmap = null;
      try{
        bitmap = NSData.dataWithContentsOfFile(file);
      } catch (err){
        logger(`base64Encode error: ${err.toString()}`)
      }

      if(!bitmap){
        return null;
      }

      return `data:image/${getFileSuffix(file)};base64,${bitmap.base64EncodedStringWithOptions(0)}`;
    }

**Comment by mathieudutour** [comment]
yeah I've never really tested it. I was planning to mirror the nodejs fs API but didn't have time to properly do it.

Happy to accept a PR to improve it tho :)

**Comment by mathieudutour** [comment]
`fs.readFileSync` now returns a `NSData`. It's up to you to get the base64 string representation from it
