### ISSUE TITLE
Access Plugin Filesystem

### ISSUE THREAD

**Issue by AdrianHigginsDev** [skpm/fs#16]
So I'm wondering how I could access the filesystem of the actual plugin rather than having to do something like save files to the /tmp/ directory.

Or if you have any other solutions.

I'm currently saving photos and license keys to the temporary directory which is very obnoxious.

**Comment by mathieudutour** [comment]
you mean accessing the path to the plugin?

You can do `process.env.plugin.url().path()`

**Comment by AdrianHigginsDev** [comment]
Thanks man, I appreciate it.
