### ISSUE TITLE
readdirSync doesn't working

### ISSUE THREAD

**Issue by nadavkaner** [skpm/fs#21]
When using readdirSync function with encoding 'buffer' as the options argument, the error occur in this line: https://github.com/skpm/fs/blob/master/index.js#L239

**Comment by mathieudutour** [comment]
what's the error?

**Comment by nadavkaner** [comment]
I guess the problem is that `pathName` value type is a string but Buffer.from expect to get another type

![image](https://user-images.githubusercontent.com/17930663/62851906-67bb1e80-bcf0-11e9-8bc6-d5db36c32e66.png)

**Comment by mathieudutour** [comment]
Ah so it's a bug in `@skpm/buffer`. I'll fix it and it will be shipped in Sketch 58.

Just by curiosity, why would you want the path names as buffers?

**Comment by nadavkaner** [comment]
It's funny because i got to this by accident because I thought it will return me the files content of the directory, but i understand that the implementation is to return the path names and not the content so it's not fit to my needs..

**Comment by mathieudutour** [comment]
Ah yep indeed, I always found this option funny for that specific method haha
