### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by TimonVS** [skpm/fs#4]
Building a plugin that uses this module results in the following error:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/876666/36643837-4ae87868-1a51-11e8-9b08-7ffd3d7f488c.png">

The issue was fixed in https://github.com/skpm/fs/pull/2. It should be solved by publishing the latest version to npm.

**Comment by mathieudutour** [comment]
done
