### ISSUE TITLE
renameSync should automatically overwrite files

### ISSUE THREAD

**Issue by jeremyblalock** [skpm/fs#7]
## Problem

[Node's implementation of `renameSync`](https://nodejs.org/api/fs.html#fs_fs_renamesync_oldpath_newpath)  automatically overwrites files, but in this implementation we throw an error if there is already a file at the destination path.

## Possible Solution

Rather than using [`moveItemAtPath`](https://developer.apple.com/documentation/foundation/nsfilemanager/1413529-moveitematpath?language=objc) we can instead use [`replaceItemAtURL`](https://developer.apple.com/documentation/foundation/nsfilemanager/1412432-replaceitematurl?language=objc) to achieve this desired behavior.

## Stop Gap

Currently, I'm having to use `existsSync` -> `renameSync` to avoid the error. This adds an extra call to the file system would be nice to avoid if possible.

**Comment by mathieudutour** [comment]
Ah yes good call! Do you want to send a PR?

**Comment by mathieudutour** [comment]
fixed in 0.2.3
